---
deployment:
  tasks:
    - export DEPLOYPATH=/home/smartpro/applications/desarrolloweb/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app components lib public package.json package-lock.json next.config.ts postcss.config.mjs tsconfig.json server.js $DEPLOYPATH
    - /usr/local/bin/npm ci --prefix $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/.next
    - /bin/cp -R .next/standalone $DEPLOYPATH/.next
    - /bin/mkdir -p $DEPLOYPATH/.next/.next/static
    - /bin/cp -R .next/static/. $DEPLOYPATH/.next/.next/static/
    - /bin/mkdir -p $DEPLOYPATH/.next/public
    - /bin/cp -R public/. $DEPLOYPATH/.next/public/
